version: "3"

services:
    dru-server:
        build: ./docker/app/ubuntu
        container_name: dru-server
        networks:
          dru_network:
            ipv4_address: 172.100.0.3
        links:
          - mysql
        volumes:
          - ./www:/var/www/html
          - ./docker/logs/apache2:/var/log/apache2
        restart: always

    mysql:
        build: ./docker/app/mysql
        container_name: dru-mysql
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: drupal
          MYSQL_PASSWORD: drupal
        networks:
          dru_network:
            ipv4_address: 172.100.0.2  
        volumes:
          - ./docker/data/mysql:/var/lib/mysql
        restart: always

    phpmyadmin:
        image: "phpmyadmin/phpmyadmin"
        container_name: dru-phpmyadmin
        ports: 
          - "9090:80"
        links:
          - mysql
        environment:
          PMA_HOST: "mysql"
          PMA_PORT: 3306
networks:
  dru_network:
    ipam:
      config:
        - subnet: 172.100.0.0/16
