version: "3"

services:
  traefik:
    image: traefik:v2.3
    command:
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      #- --certificatesresolvers.myresolver.acme.tlschallenge=true
      #- --certificatesresolvers.myresolver.acme.email=your-email@example.com
      #- --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web

  php70:
    build:
      context: ./docker/app/php-server
      dockerfile: php70/Dockerfile
    container_name: dru-server-php70
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php70.rule=HostRegexp(`{subdomain:.+}.php70.local`)"
      - "traefik.http.routers.php70.entrypoints=web"
      - "traefik.http.routers.php70-secure.rule=HostRegexp(`{subdomain:.+}.php70.local`)"
      - "traefik.http.routers.php70-secure.entrypoints=websecure"
      - "traefik.http.routers.php70-secure.tls=true"
    volumes:
      - ./www:/var/www/html
      - ./docker/logs/apache2:/var/log/apache2
      - ./docker/data/apache2/php70/sites-available:/etc/apache2/sites-available
    networks:
      - web

  php74:
    build:
      context: ./docker/app/php-server
      dockerfile: php74/Dockerfile
    container_name: dru-server-php74
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php74.rule=HostRegexp(`{subdomain:.+}.php74.local`)"
      - "traefik.http.routers.php74.entrypoints=web"
      - "traefik.http.routers.php74-secure.rule=HostRegexp(`{subdomain:.+}.php74.local`)"
      - "traefik.http.routers.php74-secure.entrypoints=websecure"
      - "traefik.http.routers.php74-secure.tls=true"
    volumes:
      - ./www:/var/www/html
      - ./docker/logs/apache2:/var/log/apache2
      - ./docker/data/apache2/php74/sites-available:/etc/apache2/sites-available
    networks:
      - web

  php81:
    build:
      context: ./docker/app/php-server
      dockerfile: php81/Dockerfile
    container_name: dru-server-php81
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php81.rule=HostRegexp(`{subdomain:.+}.php81.local`)"
      - "traefik.http.routers.php81.entrypoints=web"
      - "traefik.http.routers.php81-secure.rule=HostRegexp(`{subdomain:.+}.php81.local`)"
      - "traefik.http.routers.php81-secure.entrypoints=websecure"
      - "traefik.http.routers.php81-secure.tls=true"
    volumes:
      - ./www:/var/www/html
      - ./docker/logs/apache2:/var/log/apache2
      - ./docker/data/apache2/php81/sites-available:/etc/apache2/sites-available
    networks:
      - web

  php82:
    build:
      context: ./docker/app/php-server
      dockerfile: php82/Dockerfile
    container_name: dru-server-php82
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php82.rule=HostRegexp(`{subdomain:.+}.php82.local`)"
      - "traefik.http.routers.php82.entrypoints=web"
      - "traefik.http.routers.php82-secure.rule=HostRegexp(`{subdomain:.+}.php82.local`)"
      - "traefik.http.routers.php82-secure.entrypoints=websecure"
      - "traefik.http.routers.php82-secure.tls=true"
    volumes:
      - ./www:/var/www/html
      - ./docker/logs/apache2:/var/log/apache2
      - ./docker/data/apache2/php82/sites-available:/etc/apache2/sites-available
    networks:
      - web

  mysql:
    build: ./docker/app/mysql
    container_name: dru-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    ports:
      - "3306:3306"
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    networks:
      - web

  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    container_name: dru-phpmyadmin
    ports:
      - "9090:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    networks:
      - web

  mailhog:
    image: mailhog/mailhog
    container_name: dru-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - web

# Uncomment the solr service configuration if needed.
#  solr:
#     image: solr:5.5
#     container_name: dru-solr
#     ports:
#       - 8983:8983
#     volumes:
#       - ./docker/data/solr:/opt/solr/server/solr/mycores
#     networks:
#       - web

networks:
  web:
    # This network will be created with the default
