version: "3"

services:
    dru-server:
        build: ./docker/app/ubuntu
        container_name: dru-server
        ports: 
          - 80:80
          - 443:443
        links:
          - mariadb
          - mailhog
        volumes:
          - ./www:/var/www/html
          - ./docker/logs/apache2:/var/log/apache2
          - ./docker/app/ubuntu/apache2/sites-available:/etc/apache2/sites-available
        restart: always

    mariadb:
        build: ./docker/app/mariadb
        container_name: dru-mariadb
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: drupal
          MYSQL_PASSWORD: drupal
        ports: 
          - 3306:3306
        volumes:
          - ./docker/data/mysql:/var/lib/mysql
        restart: always
    

    phpmyadmin:
        image: "phpmyadmin/phpmyadmin"
        container_name: dru-phpmyadmin
        ports: 
          - "9090:80"
        links:
          - mariadb
        environment:
          PMA_HOST: "mariadb"
          PMA_PORT: 3306
    mailhog: 
        image: mailhog/mailhog
        container_name: dru-mailhog
        ports: 
          - 1025:1025
          - 8025:8025
    solr:
        image: solr:5.5
        container_name: dru-solr
        ports:
          - 8983:8983
        volumes:
          - ./docker/data/solr:/opt/solr/server/solr/mycores
      
