version: "3"

services:
    dru-server:
        build: ./docker/app/ubuntu
        container_name: dru-server
        ports: 
          - 80:80
          - 443:443
        links:
          - mysql
          - mailhog
        volumes:
          - ./www:/var/www/html
          - ./docker/logs/apache2:/var/log/apache2
          - ./docker/app/ubuntu/apache2/sites-available:/etc/apache2/sites-available
        restart: always

    mysql:
        build: ./docker/app/mysql
        container_name: dru-mysql
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: drupal
          MYSQL_PASSWORD: drupal
        ports: 
          - 3306:3306
        volumes:
          - ./docker/data/mysql:/var/lib/mysql
        restart: always

    phpmyadmin:
        image: "phpmyadmin/phpmyadmin"
        container_name: dru-phpmyadmin
        ports: 
          - "9090:80"
        links:
          - mysql
        environment:
          PMA_HOST: "mysql"
          PMA_PORT: 3306
    mailhog: 
        image: mailhog/mailhog
        container_name: dru-mailhog
        ports: 
          - 1025:1025
          - 8025:8025
